# Generated by Django 5.0.3 on 2024-04-02 07:12

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[gallery.models.validate_image_extension]),
        ),
    ]
